// Generated by Shinro (format 3). Do not edit.
import { hc } from "hono/client";

import type app from "../src/app.ts";

type AppType = typeof app;

const typedClient = hc<AppType>("");

export type Client = typeof typedClient;
export type { AppType };

export const defineClient = (...args: Parameters<typeof hc>): Client =>
  hc<AppType>(...args);

export type { InferRequestType, InferResponseType } from "hono/client";
