// Generated by Shinro (format 3). Do not edit.
import { Hono } from "hono";
import type { ProjectEnv } from "shinro/app";
import { GET as route0GET } from "../src/routes/index.ts";
import route0Middleware0 from "../src/routes/_middleware.ts";
import { GET as route1GET } from "../src/routes/health.ts";
import route1Middleware0 from "../src/routes/_middleware.ts";
import { GET as route2GET } from "../src/routes/users/index.ts";
import { POST as route2POST } from "../src/routes/users/index.ts";
import route2Middleware0 from "../src/routes/_middleware.ts";
import { GET as route3GET } from "../src/routes/users/$id.ts";
import route3Middleware0 from "../src/routes/_middleware.ts";

export function routes() {
  return new Hono<ProjectEnv>()
    .get("/v1", ...route0Middleware0, ...route0GET)
    .get("/v1/health", ...route1Middleware0, ...route1GET)
    .get("/v1/users", ...route2Middleware0, ...route2GET)
    .post("/v1/users", ...route2Middleware0, ...route2POST)
    .get("/v1/users/:id", ...route3Middleware0, ...route3GET);
}

export type Routes = ReturnType<typeof routes>;
