// Generated by Shinro (format 3). Do not edit.
import type { ShinroMiddleware, ProjectEnv } from "shinro/app";

export namespace Route {
  export type Middleware = ShinroMiddleware<{
    path: "/v1";
    env: ProjectEnv;
  }>;
}
