/** Declared in the app's `package.json` `imports` block; Node, tsc, tsx, bun and
 * rolldown all resolve it. Shinro only checks it points at `.shinro/routes.ts`. */
export const ROUTES_SPECIFIER = '#shinro/routes';
export const CLIENT_SPECIFIER = '#shinro/client';
export const ROUTES_FILE = 'routes.ts';
export const CLIENT_FILE = 'client.ts';
export const MANIFEST_FILE = 'manifest.json';
export const OUTPUT_DIRECTORY = '.shinro';
/** Where a route imports its own types from, and the directory they live in. */
export const TYPE_DECLARATION_PREFIX = '+types';
/** Matched against the raw text, in either the string or the array form: tsconfig
 * is JSONC, and a parser plus an extends-chain resolver is a lot of dependency
 * for a question the string already answers. */
export const EXTENDS_SHIPPED_TSCONFIG =
  /"extends"\s*:\s*(?:"shinro\/tsconfig|\[[^\]]*"shinro\/tsconfig)/;
/** Registration order, and Hono runs the first match: `ALL` is last so a file
 * exporting both serves GET from `GET` and every other verb from `ALL`. */
export const HTTP_METHODS = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'OPTIONS',
  'ALL',
] as const;
export type Method = (typeof HTTP_METHODS)[number];
/** Bumped whenever a generated file changes shape, so `--check` can tell a stale
 * tree apart from an upgrade — the same byte diff, completely different fixes. */
export const GENERATED_FORMAT = 3;
export const GENERATED_NOTICE = `// Generated by Shinro (format ${GENERATED_FORMAT}). Do not edit.`;
/** Matches any format's notice: an upgraded project's leftovers carry an older
 * number, and a file without one belongs to the user and is never touched. */
export const GENERATED_NOTICE_PATTERN =
  /^\/\/ Generated by Shinro \(format (\d+)\)\. Do not edit\./;
/** Files an earlier format wrote that this one does not. A stale `shinro.d.ts`
 * keeps type-checking after the thing it describes is gone. */
export const LEGACY_FILES = [
  'shinro.d.ts',
  'rpc.ts',
  'entry.ts',
  'modules.d.ts',
] as const;
/** Hono's typed `HandlerInterface` overloads stop at path plus ten handlers. Past
 * that a variadic fallback infers one shared `Input` for the whole chain, so the
 * generated client loses every validator's contribution, silently. */
export const HONO_HANDLER_LIMIT = 10;
/** The staging directory every generation is assembled in before promotion. */
export const STAGING_DIRECTORY = '.staging';
