export const ROUTES_ID = 'shinro/routes';
export const ROUTES_FILE = 'routes.ts';
export const CLIENT_ID = 'shinro/client';
export const CLIENT_FILE = 'client.ts';
export const RPC_ID = 'shinro/rpc';
export const RPC_FILE = 'rpc.ts';
export const MODULES_FILE = 'shinro.d.ts';
/**
 * Order matters: routes register in this order, and Hono runs the first
 * matching handler. `ALL` is last so a file exporting both `GET` and `ALL`
 * serves GET from `GET` and every other verb from `ALL`.
 */
export const HTTP_METHODS = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'OPTIONS',
  'ALL',
] as const;
export const GENERATED_NOTICE =
  '// Generated by Shinro (format 2). Do not edit.';
/**
 * Matches the notice of any format, not just the current one. Stale files are
 * recognised by this marker before being deleted, and an upgraded project's
 * leftovers necessarily carry an older format number.
 */
export const GENERATED_NOTICE_PATTERN =
  /^\/\/ Generated by Shinro \(format \d+\)\. Do not edit\./;
/**
 * Files an earlier format generated that this one does not. Removed on every
 * generation so an upgraded project does not keep a `shinro/entry` declaration
 * pointing at a route table nothing maintains.
 */
export const LEGACY_FILES = ['entry.ts', 'modules.d.ts'] as const;
/**
 * Every top-level name Shinro may own inside its generated directory,
 * including the transient lock and the names earlier formats used. Used to tell
 * an existing generated directory apart from a directory that holds someone
 * else's files, so the check cannot be fooled by a generation that is still in
 * progress or by output this version no longer writes.
 */
export const GENERATED_ENTRIES = [
  '.lock',
  CLIENT_FILE,
  MODULES_FILE,
  ROUTES_FILE,
  RPC_FILE,
  'manifest.json',
  'types',
  ...LEGACY_FILES,
] as const;
