/**
 * The specifier the app's `package.json` `imports` block declares. Nothing in
 * Shinro resolves it — Node, tsc, tsx, bun, and rolldown all do, because
 * `imports` is part of ESM resolution rather than a bundler feature. Shinro only
 * checks it points at `.shinro/routes.ts`.
 */
export const ROUTES_SPECIFIER = '#shinro/routes';
export const CLIENT_SPECIFIER = '#shinro/client';
export const ROUTES_FILE = 'routes.ts';
export const CLIENT_FILE = 'client.ts';
export const MANIFEST_FILE = 'manifest.json';
export const OUTPUT_DIRECTORY = '.shinro';
/** Where a route imports its own types from, and the directory they live in. */
export const TYPE_DECLARATION_PREFIX = '+types';
/**
 * Order matters: routes register in this order, and Hono runs the first
 * matching handler. `ALL` is last so a file exporting both `GET` and `ALL`
 * serves GET from `GET` and every other verb from `ALL`.
 */
export const HTTP_METHODS = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'OPTIONS',
  'ALL',
] as const;
/**
 * Bumped from 2 because `shinro.d.ts` disappeared and the specifier changed —
 * both breaking. The number is not decoration: `generate --check` reads it to
 * tell "these artifacts are stale" apart from "these artifacts were written by
 * a different version of Shinro", which are the same byte diff and completely
 * different fixes.
 */
export const GENERATED_FORMAT = 3;
export const GENERATED_NOTICE = `// Generated by Shinro (format ${GENERATED_FORMAT}). Do not edit.`;
/**
 * Matches any format's notice, not just the current one. Stale files are
 * recognised by this marker before being deleted, and an upgraded project's
 * leftovers necessarily carry an older number. A file without one belongs to
 * the user and is never touched.
 */
export const GENERATED_NOTICE_PATTERN =
  /^\/\/ Generated by Shinro \(format (\d+)\)\. Do not edit\./;
/**
 * Files an earlier format wrote that this one does not. `shinro.d.ts` declared
 * the bare `shinro/routes` specifier against a plugin-provided `resolveId`, and
 * `rpc.ts` was a second derivation of `AppType`; leaving either behind is worse
 * than deleting it, because both keep type-checking after the thing they
 * describe is gone.
 */
export const LEGACY_FILES = [
  'shinro.d.ts',
  'rpc.ts',
  'entry.ts',
  'modules.d.ts',
] as const;
/**
 * Hono's typed `HandlerInterface` overloads stop at path plus ten handlers.
 * Past that a variadic fallback takes over: it still runs, and it still
 * type-checks, but it infers one shared `Input` for the whole chain, so the
 * generated client loses every validator's contribution. Nothing warns. This is
 * the ceiling `generate` enforces, since generate is the only place that knows
 * the emitted arity.
 */
export const HONO_HANDLER_LIMIT = 10;
/** The staging directory every generation is assembled in before promotion. */
export const STAGING_DIRECTORY = '.staging';
