import type { InferResponseType } from 'hono/client';
import { testClient } from 'hono/testing';
import { expect, expectTypeOf, test } from 'vite-plus/test';

import { defineClient } from '../.shinro/client.ts';
import app from './fixtures/basic/src/app.ts';

// The fixture application, assembled the way a real one is: `.shinro` is
// generated by `vp run generate` (wired to `pretest`), the app imports it through
// `#shinro/routes`, and nothing in this file knows how generation happened.
const client = testClient(app);

test('mounting the generated router keeps one Hono instance', () => {
  const paths = app.routes.map((route) => route.path);

  expect(paths).toContain('/health');
  expect(paths).toContain('/manual');
});

test('a GET route is discovered, assembled, and available to the RPC client', async () => {
  const response = await client.health.$get();

  expect(response.status).toBe(200);
  await expect(response.json()).resolves.toEqual({ ok: true });
});

test('HEAD uses the matching GET route and omits its response body', async () => {
  const response = await app.request('/health', { method: 'HEAD' });

  expect(response.status).toBe(200);
  await expect(response.text()).resolves.toBe('');
});

test('one route module can expose multiple HTTP methods', async () => {
  const response = await client.health.$post();

  expect(response.status).toBe(201);
  await expect(response.json()).resolves.toEqual({ created: true });
});

test('PUT, PATCH, DELETE, and OPTIONS exports reach runtime and RPC', async () => {
  await expect(client.verbs.$put().then((r) => r.json())).resolves.toEqual({
    method: 'PUT',
  });
  await expect(client.verbs.$patch().then((r) => r.json())).resolves.toEqual({
    method: 'PATCH',
  });
  await expect(client.verbs.$delete().then((r) => r.json())).resolves.toEqual({
    method: 'DELETE',
  });
  await expect(client.verbs.$options().then((r) => r.json())).resolves.toEqual({
    method: 'OPTIONS',
  });
});

test('the app environment types route handlers without a repeated generic', async () => {
  const response = await client.whoami.$get();

  await expect(response.json()).resolves.toEqual({ requestId: 'req_123' });
});

test('chained manual Hono routes remain available on the assembled app', async () => {
  const response = await client.manual.$get();

  await expect(response.json()).resolves.toEqual({ manual: true });
});

test('directory middleware runs, in order, for its directory and descendants', async () => {
  const response = await app.request('/api');

  expect(response.headers.get('x-middleware-order')).toBe('first,second');
  await expect(response.json()).resolves.toEqual({ route: 'api' });

  const descendant = await app.request('/api/users');
  expect(descendant.headers.get('x-middleware-order')).toBe('first,second');

  const outside = await app.request('/health');
  expect(outside.headers.get('x-middleware-order')).toBeNull();
});

test('composing directory middleware preserves a short circuit', async () => {
  const denied = await app.request('/secure');
  expect(denied.status).toBe(401);
  await expect(denied.json()).resolves.toEqual({ error: 'UNAUTHORIZED' });

  const allowed = await app.request('/secure', {
    headers: { authorization: 'Bearer valid' },
  });
  expect(allowed.status).toBe(200);
  await expect(allowed.json()).resolves.toEqual({ secret: true });
});

test('directory middleware responses are part of the RPC response union', () => {
  // The middleware short-circuits with a 401, and composing it through `every()`
  // keeps that response in the contract rather than collapsing it.
  expectTypeOf<
    InferResponseType<typeof client.secure.$get, 401>
  >().toEqualTypeOf<{ error: 'UNAUTHORIZED' }>();
});

test('a group directory wraps its routes without entering the URL', async () => {
  const response = await client.scoped.$get();

  expect(response.status).toBe(200);
  expect(response.headers.get('x-group')).toBe('grouped');
  await expect(response.json()).resolves.toEqual({ scoped: true });
});

test('a default Hono sub-router runs at its mount and appears on the client', async () => {
  await expect(client.admin.$get().then((r) => r.json())).resolves.toEqual({
    section: 'admin',
  });
  await expect(
    client.admin.stats.$get().then((r) => r.json())
  ).resolves.toEqual({ activeUsers: 42 });
});

test('route-local middleware runs before the handler it is bundled with', async () => {
  const response = await client.pipeline.$get();

  expect(response.headers.get('x-pipeline-first')).toBe('yes');
  expect(response.headers.get('x-pipeline-second')).toBe('yes');
  await expect(response.json()).resolves.toEqual({ complete: true });
});

test('route-local middleware can set a variable the handler reads', async () => {
  await expect(client.local.$get().then((r) => r.json())).resolves.toEqual({
    requestId: 'req_local',
  });
});

test('a dynamic segment reaches the handler and the client as a parameter', async () => {
  const response = await client.api.users[':id'].$get({
    param: { id: 'u_1' },
  });

  await expect(response.json()).resolves.toEqual({ id: 'u_1' });
});

test('nested dynamic directories contribute typed parameters', async () => {
  const response = await client.teams[':teamId'].members[':memberId'].$get({
    param: { memberId: 'm_2', teamId: 't_1' },
  });

  await expect(response.json()).resolves.toEqual({
    memberId: 'm_2',
    teamId: 't_1',
  });
});

test('a catch-all route captures one or more path segments', async () => {
  const response = await app.request('/files/a/b/c.txt');

  await expect(response.json()).resolves.toEqual({ path: 'a/b/c.txt' });
});

test('a validator provides runtime and RPC parameter validation', async () => {
  const valid = await client.validated[':id'].$get({ param: { id: 'abc' } });
  expect(valid.status).toBe(200);
  await expect(valid.json()).resolves.toEqual({ id: 'abc' });

  const invalid = await app.request('/validated/ab');
  expect(invalid.status).toBe(400);
});

test('two validators accumulate into the handler and the RPC contract', async () => {
  const response = await client.validated[':id'].$patch({
    json: { name: 'Ada' },
    param: { id: 'abc' },
  });

  expect(response.status).toBe(200);
  await expect(response.json()).resolves.toEqual({ id: 'abc', name: 'Ada' });
});

test('a test file inside the routes directory is not a route', () => {
  expect(app.routes.map((route) => route.path)).not.toContain(
    '/ignored.spec.route'
  );
});

test('the generated client exposes the assembled application contract', () => {
  const generated = defineClient('http://localhost');

  expectTypeOf(generated.health.$get).toBeFunction();
  expectTypeOf(generated.manual.$get).toBeFunction();
  expectTypeOf(generated.admin.stats.$get).toBeFunction();
});

test('the generated client keeps each validator in the request contract', () => {
  const generated = defineClient('http://localhost');

  expectTypeOf(generated.validated[':id'].$patch)
    .parameter(0)
    .toMatchObjectType<{ json: { name: string }; param: { id: string } }>();
});
