import { spawn } from 'node:child_process';
import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

import { expect, test } from 'vite-plus/test';

test('the CLI reports the supported typegen command', async () => {
  const result = await run(process.execPath, [
    fileURLToPath(new URL('../src/cli.ts', import.meta.url)),
    'unknown',
  ]);

  expect(result.code).toBe(1);
  expect(result.stderr).toContain('daroyan typegen');
});

test('typegen fails clearly when the Vite config does not install daroyan', async () => {
  const root = await mkdtemp(`${tmpdir()}/daroyan-cli-no-plugin-`);

  try {
    const result = await run(
      process.execPath,
      [fileURLToPath(new URL('../src/cli.ts', import.meta.url)), 'typegen'],
      root
    );

    expect(result.code).toBe(1);
    expect(result.stderr).toMatch(
      /typegen[\s\S]*vite config[\s\S]*daroyan\(\)/i
    );
  } finally {
    await rm(root, { recursive: true });
  }
});

test('typegen prepares every generated type artifact in a clean checkout', async () => {
  const packageRoot = fileURLToPath(new URL('..', import.meta.url));
  const root = await mkdtemp(`${packageRoot}/.daroyan-cli-typegen-`);
  const plugin = fileURLToPath(new URL('../src/index.ts', import.meta.url));
  const appHelper = fileURLToPath(new URL('../src/app.ts', import.meta.url));

  await mkdir(`${root}/src/routes/users`, { recursive: true });
  await writeFile(
    `${root}/vite.config.ts`,
    [
      `import { daroyan } from ${JSON.stringify(plugin)};`,
      'import { defineConfig } from "vite-plus";',
      'export default defineConfig({ plugins: [daroyan()] });',
      '',
    ].join('\n')
  );
  await writeFile(
    `${root}/src/app.ts`,
    [
      'import { defineApp } from "daroyan/app";',
      'type AppEnv = { Variables: { requestId: string } };',
      'export default defineApp<AppEnv>();',
      '',
    ].join('\n')
  );
  await writeFile(
    `${root}/src/routes/users/$id.ts`,
    [
      'import { defineHandler } from "daroyan/app";',
      'import type { Route } from "./+types/$id.ts";',
      'export const GET = defineHandler<Route.Handler>((c) => {',
      '  const id: string = c.req.param("id");',
      '  const requestId: string = c.var.requestId;',
      '  // @ts-expect-error An unknown filename parameter is possibly undefined.',
      '  const missing: string = c.req.param("missing");',
      '  // @ts-expect-error Route is a namespace, not the removed route contract alias.',
      '  const legacy: Route = {};',
      '  return c.json({ id, legacy, missing, requestId });',
      '});',
      '',
    ].join('\n')
  );
  await writeFile(
    `${root}/src/routes/users/_middleware.ts`,
    [
      'import { defineMiddleware } from "daroyan/app";',
      'import type { Route } from "./+types/_middleware.ts";',
      '// @ts-expect-error The old top-level middleware alias was removed.',
      'import type { Middleware } from "./+types/_middleware.ts";',
      'export default defineMiddleware<Route.Middleware>(',
      '  async (c, next) => {',
      '    const requestId: string = c.var.requestId;',
      '    void requestId;',
      '    await next();',
      '  },',
      '  async (_c, next) => { await next(); },',
      ');',
      'type LegacyMiddleware = Middleware;',
      '',
    ].join('\n')
  );
  await writeFile(
    `${root}/tsconfig.json`,
    JSON.stringify({
      compilerOptions: {
        allowImportingTsExtensions: true,
        module: 'ESNext',
        moduleResolution: 'Bundler',
        noEmit: true,
        paths: {
          'daroyan/app': [appHelper],
        },
        rootDirs: ['.', './.daroyan/types'],
        strict: true,
      },
      include: ['src', '.daroyan/**/*.d.ts'],
    })
  );

  try {
    const result = await run(
      process.execPath,
      [fileURLToPath(new URL('../src/cli.ts', import.meta.url)), 'typegen'],
      root
    );

    expect(result.code).toBe(0);
    for (const file of [
      '.daroyan/client.ts',
      '.daroyan/daroyan.d.ts',
      '.daroyan/manifest.json',
      '.daroyan/rpc.ts',
      '.daroyan/entry.ts',
      '.daroyan/types/app.d.ts',
      '.daroyan/modules.d.ts',
      '.daroyan/types/src/routes/users/+types/_middleware.d.ts',
      '.daroyan/types/src/routes/users/+types/$id.d.ts',
    ]) {
      await expect(readFile(`${root}/${file}`, 'utf8')).resolves.toContain(
        'Generated by Daroyan (format 1)'
      );
    }

    await expect(
      readFile(`${root}/.daroyan/entry.ts`, 'utf8')
    ).resolves.toContain('from "../src/routes/users/$id.ts";');
    await expect(
      readFile(`${root}/.daroyan/entry.ts`, 'utf8')
    ).resolves.toContain('from "../src/routes/users/_middleware.ts";');
    await expect(
      readFile(`${root}/.daroyan/rpc.ts`, 'utf8')
    ).resolves.toContain('from "./entry.ts";');
    await expect(
      readFile(`${root}/.daroyan/daroyan.d.ts`, 'utf8')
    ).resolves.toContain('from "../src/app.ts";');
    await expect(
      readFile(`${root}/.daroyan/types/app.d.ts`, 'utf8')
    ).resolves.toContain('from "../../src/app.ts";');

    const typecheck = await run(
      `${packageRoot}/node_modules/.bin/tsc`,
      ['--noEmit'],
      root
    );
    expect(typecheck.code, `${typecheck.stdout}${typecheck.stderr}`).toBe(0);
  } finally {
    await rm(root, { recursive: true });
  }
});

test('concurrent typegen processes commit one complete generated directory', async () => {
  const packageRoot = fileURLToPath(new URL('..', import.meta.url));
  const root = await mkdtemp(`${packageRoot}/.daroyan-concurrent-typegen-`);
  const plugin = fileURLToPath(new URL('../src/index.ts', import.meta.url));
  const appHelper = fileURLToPath(new URL('../src/app.ts', import.meta.url));
  const cli = fileURLToPath(new URL('../src/cli.ts', import.meta.url));

  await mkdir(`${root}/src/routes`, { recursive: true });
  await writeFile(
    `${root}/vite.config.ts`,
    [
      `import { daroyan } from ${JSON.stringify(plugin)};`,
      'import { defineConfig } from "vite-plus";',
      'export default defineConfig({ plugins: [daroyan()] });',
      '',
    ].join('\n')
  );
  await writeFile(
    `${root}/src/app.ts`,
    `import { defineApp } from ${JSON.stringify(appHelper)};\nexport default defineApp();\n`
  );
  await Promise.all(
    Array.from({ length: 40 }, (_, index) =>
      writeFile(
        `${root}/src/routes/route-${index}.ts`,
        `export const GET = [(c: any) => c.json({ route: ${index} })] as const;\n`
      )
    )
  );

  try {
    const results = await Promise.all(
      Array.from({ length: 8 }, () =>
        run(process.execPath, [cli, 'typegen'], root)
      )
    );

    expect(
      results.map((result) => result.code),
      results.map((result) => `${result.stdout}${result.stderr}`).join('\n')
    ).toEqual(Array.from({ length: 8 }, () => 0));

    const manifest = JSON.parse(
      await readFile(`${root}/.daroyan/manifest.json`, 'utf8')
    ) as {
      routes: unknown[];
    };
    expect(manifest.routes).toHaveLength(40);
    expect(
      (await readdir(root)).filter((name) => name.startsWith('.daroyan.'))
    ).toEqual([]);
  } finally {
    await rm(root, { recursive: true });
  }
}, 20_000);

function run(
  command: string,
  args: string[],
  cwd = fileURLToPath(new URL('..', import.meta.url))
): Promise<{
  code: number | null;
  stderr: string;
  stdout: string;
}> {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stderr = '';
    let stdout = '';

    child.stdout.setEncoding('utf8');
    child.stdout.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', (chunk: string) => {
      stderr += chunk;
    });
    child.on('close', (code) => {
      resolve({ code, stderr, stdout });
    });
  });
}
