import { spawn } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { expect, test } from "vite-plus/test";

test("the CLI reports the supported typegen command", async () => {
  const result = await run(process.execPath, [
    fileURLToPath(new URL("../src/cli.ts", import.meta.url)),
    "unknown",
  ]);

  expect(result.code).toBe(1);
  expect(result.stderr).toContain("daroyan typegen");
});

test("typegen fails clearly when the Vite config does not install daroyan", async () => {
  const root = await mkdtemp(`${tmpdir()}/daroyan-cli-no-plugin-`);

  try {
    const result = await run(
      process.execPath,
      [fileURLToPath(new URL("../src/cli.ts", import.meta.url)), "typegen"],
      root,
    );

    expect(result.code).toBe(1);
    expect(result.stderr).toMatch(/typegen[\s\S]*vite config[\s\S]*daroyan\(\)/i);
  } finally {
    await rm(root, { recursive: true });
  }
});

test("typegen prepares every generated type artifact in a clean checkout", async () => {
  const packageRoot = fileURLToPath(new URL("..", import.meta.url));
  const root = await mkdtemp(`${packageRoot}/.daroyan-cli-typegen-`);
  const plugin = fileURLToPath(new URL("../src/index.ts", import.meta.url));
  const appHelper = fileURLToPath(new URL("../src/app.ts", import.meta.url));

  await mkdir(`${root}/app/routes/users`, { recursive: true });
  await writeFile(
    `${root}/vite.config.ts`,
    [
      `import { daroyan } from ${JSON.stringify(plugin)};`,
      'import { defineConfig } from "vite-plus";',
      "export default defineConfig({ plugins: [daroyan()] });",
      "",
    ].join("\n"),
  );
  await writeFile(
    `${root}/app/app.ts`,
    `import { defineApp } from ${JSON.stringify(appHelper)};\nexport default defineApp();\n`,
  );
  await writeFile(
    `${root}/app/routes/users/$id.ts`,
    [
      'import { defineHandler } from "daroyan/app";',
      'import type { Route } from "./+types/$id";',
      "export const GET = defineHandler<Route>((c) => {",
      '  const id: string = c.req.param("id");',
      "  // @ts-expect-error An unknown filename parameter is possibly undefined.",
      '  const missing: string = c.req.param("missing");',
      "  return c.json({ id, missing });",
      "});",
      "",
    ].join("\n"),
  );
  await writeFile(
    `${root}/tsconfig.json`,
    JSON.stringify({
      compilerOptions: {
        allowImportingTsExtensions: true,
        module: "ESNext",
        moduleResolution: "Bundler",
        noEmit: true,
        paths: {
          "daroyan/app": [appHelper],
        },
        rootDirs: [".", "./.daroyan/types"],
        strict: true,
      },
      include: ["app", ".daroyan/**/*.d.ts"],
    }),
  );

  try {
    const result = await run(
      process.execPath,
      [fileURLToPath(new URL("../src/cli.ts", import.meta.url)), "typegen"],
      root,
    );

    expect(result.code).toBe(0);
    for (const file of [
      ".daroyan/client.ts",
      ".daroyan/daroyan.d.ts",
      ".daroyan/manifest.json",
      ".daroyan/rpc.ts",
      ".daroyan/types/app.d.ts",
      ".daroyan/types/entry.d.ts",
      ".daroyan/types/app/routes/users/+types/$id.d.ts",
    ]) {
      await expect(readFile(`${root}/${file}`, "utf8")).resolves.toContain(
        "Generated by Daroyan (format 1)",
      );
    }

    const typecheck = await run(`${packageRoot}/node_modules/.bin/tsc`, ["--noEmit"], root);
    expect(typecheck.code).toBe(0);
  } finally {
    await rm(root, { recursive: true });
  }
});

function run(
  command: string,
  args: string[],
  cwd = fileURLToPath(new URL("..", import.meta.url)),
): Promise<{
  code: number | null;
  stderr: string;
}> {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";

    child.stderr.setEncoding("utf8");
    child.stderr.on("data", (chunk: string) => {
      stderr += chunk;
    });
    child.on("close", (code) => {
      resolve({ code, stderr });
    });
  });
}
