packages:
  - apps/*
  - examples/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: ^4.0.0
  vite-plus: latest
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  '@hono/zod-validator': ^0.9.0
  zod: ^4.4.3
  '@hono/node-server': ^2.0.11
  '@fontsource-variable/inter': ^5.3.0
  '@fontsource-variable/jetbrains-mono': ^5.3.0
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  esbuild: true
  sharp: true
