import { relative } from 'node:path';

import { findProjectRoot, loadConfig } from '../config.ts';
import { GENERATED_FORMAT } from '../constants.ts';
import { generate as generateCore } from '../core/generate.ts';
import { createLogger } from '../core/logger.ts';
import { watch } from '../core/watch.ts';

/**
 * `shinro generate [--watch] [--check]`
 *
 * The product. No `resolveConfig` from Vite, no plugin lookup, no dev server:
 * load config, generate, exit.
 *
 * Named for the core function it calls. The old name, `typegen`, described a
 * third of the output — `.shinro/routes.ts` is runtime code, and telling people
 * the router is a type artifact is the one belief this design can't afford.
 * `typegen` still resolves, undocumented, so existing scripts keep running.
 *
 * `--watch` debounces a watcher on the routes directory and regenerates. It
 * spawns nothing and restarts nothing; the runner is the user's business. It
 * generates once, synchronously, before it starts watching, so the artifacts
 * exist by the time anything else reads them. Only needed for a runner that
 * can't do either half itself — with `node --watch`, `shinro/watch` as an
 * `--import` preload covers dev in one process.
 *
 * `--check` generates into memory and compares against disk. Exits non-zero on
 * a route conflict, an invalid module, or a stale artifact, and writes nothing.
 * Once no bundler is guaranteed to run this is the only place a conflict can be
 * caught, so it is the CI gate — and it is what makes committing `.shinro/` a
 * supported choice rather than a trap.
 */
export async function generate(argv: string[]): Promise<number> {
  const logger = createLogger();
  const flags = new Set(argv.filter((argument) => argument.startsWith('-')));
  const unknown = [...flags].filter(
    (flag) => flag !== '--watch' && flag !== '--check'
  );

  if (unknown.length > 0) {
    logger.error(
      `[shinro] Unknown option ${unknown.join(', ')}.\nUsage: shinro generate [--watch] [--check]`
    );
    return 1;
  }

  if (flags.has('--watch') && flags.has('--check')) {
    logger.error(
      '[shinro] --watch and --check are mutually exclusive: one writes whenever the tree changes, the other never writes.'
    );
    return 1;
  }

  const root = await findProjectRoot();

  try {
    const config = await loadConfig(root, logger);

    if (flags.has('--watch')) {
      await watch({
        config,
        // A watcher that exits on the typo it was started to catch is a worse
        // tool than one that prints it and stays up.
        initial: 'report',
        // The one place the watcher may hold the event loop open: here it is the
        // whole process, rather than a passenger in someone's server.
        keepAlive: true,
        logger,
        onGenerate: (result) => {
          for (const file of result.written) {
            logger.info(`[shinro] wrote ${relative(root, file)}`);
          }
          for (const file of result.removed) {
            logger.info(`[shinro] removed ${relative(root, file)}`);
          }
        },
      });
      logger.info(`[shinro] watching ${config.routes}`);
      // Never resolves; the watcher holds the event loop open. Nothing here
      // installs a signal handler, so Ctrl-C behaves the way Ctrl-C behaves.
      return await new Promise<number>(() => {});
    }

    const result = await generateCore({
      check: flags.has('--check'),
      config,
      logger,
    });
    const drifted = [...result.written, ...result.removed];

    if (!flags.has('--check')) {
      logger.info(
        drifted.length === 0
          ? `[shinro] ${relative(root, result.outputDirectory)} is up to date`
          : `[shinro] wrote ${relative(root, result.outputDirectory)}`
      );
      return 0;
    }

    if (drifted.length === 0) {
      logger.info(
        `[shinro] ${relative(root, result.outputDirectory)} matches the route tree`
      );
      return 0;
    }

    // Stale artifacts and a package upgrade produce the same byte diff and want
    // opposite reactions, so the format number decides which message this is.
    // Without it, a committed `.shinro/` becomes the confusing part of an
    // upgrade.
    logger.error(
      result.onDiskFormat === undefined
        ? [
            `[shinro] ${relative(root, result.outputDirectory)} is out of date. Run "shinro generate".`,
            ...drifted.map((file) => `- ${relative(root, file)}`),
          ].join('\n')
        : `[shinro] ${relative(root, result.outputDirectory)} was generated by an older shinro (format ${result.onDiskFormat}, this is format ${GENERATED_FORMAT}). Run "shinro generate" and commit the result.`
    );
    return 1;
  } catch (error) {
    logger.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}
