import { relative, resolve } from 'node:path';

import { defineCommand } from 'citty';

import type { ResolvedShinroConfig } from '../config.ts';
import { findProjectRoot, loadConfig } from '../config.ts';
import { GENERATED_FORMAT } from '../constants.ts';
import { generate as generateCore, readManifest } from '../core/generate.ts';
import type { ShinroLogger } from '../core/logger.ts';
import { watch } from '../core/watch.ts';
import { unknownOptions } from './args.ts';
import { createReporter } from './report.ts';
import { dim, green } from './style.ts';
import { routeTree } from './tree.ts';

/** `--watch` regenerates whenever the route tree changes, spawning nothing.
 * `--check` compares against disk and writes nothing: the CI gate that makes
 * committing `.shinro/` a supported choice. */
export const generate = defineCommand({
  args: {
    check: {
      description:
        'Compare against disk, write nothing, exit non-zero if stale',
      type: 'boolean',
    },
    tree: {
      description: 'Print the route tree instead of just the count',
      type: 'boolean',
    },
    watch: {
      description: 'Regenerate whenever the route tree changes',
      type: 'boolean',
    },
  },
  meta: {
    description: 'Write .shinro from the route tree',
    name: 'generate',
  },
  async run({ args, rawArgs }) {
    const unknown = unknownOptions(rawArgs, ['--check', '--tree', '--watch']);

    if (unknown.length > 0) {
      createReporter().error(
        `[shinro] Unknown option ${unknown.join(', ')}.\nUsage: shinro generate [--watch] [--check] [--tree]`
      );
      process.exitCode = 1;
      return;
    }

    process.exitCode = await run({
      check: args.check,
      tree: args.tree,
      watch: args.watch,
    });
  },
});

export const typegen = defineCommand({
  args: generate.args,
  meta: {
    description: 'Deprecated alias for generate',
    hidden: true,
    name: 'typegen',
  },
  run: generate.run,
});

async function run(flags: {
  check?: boolean;
  tree?: boolean;
  watch?: boolean;
}): Promise<number> {
  const logger = createReporter();

  if (flags.watch === true && flags.check === true) {
    logger.error(
      '[shinro] --watch and --check are mutually exclusive: one writes whenever the tree changes, the other never writes.'
    );
    return 1;
  }

  const root = await findProjectRoot();

  try {
    const config = await loadConfig(root, logger);

    if (flags.watch === true) {
      return await runWatch(config, logger, root);
    }

    const result = await generateCore({
      check: flags.check === true,
      config,
      logger,
    });
    const drifted = [...result.written, ...result.removed];

    if (flags.check !== true) {
      const routes = (await readManifest(config.outputDirectory))?.routes ?? [];
      const where = relative(root, result.outputDirectory);

      logger.info(
        `${
          drifted.length === 0
            ? `[shinro] ${where} is up to date`
            : `[shinro] wrote ${where}`
        }${dim(` · ${count(routes.length)}`)}`
      );

      if (flags.tree === true) {
        console.info(['', ...routeTree(routes), ''].join('\n'));
      }
      return 0;
    }

    if (drifted.length === 0) {
      logger.info(
        `[shinro] ${relative(root, result.outputDirectory)} matches the route tree`
      );
      return 0;
    }

    logger.error(
      result.onDiskFormat === undefined
        ? [
            `[shinro] ${relative(root, result.outputDirectory)} is out of date. Run "shinro generate".`,
            ...drifted.map((file) => `- ${relative(root, file)}`),
          ].join('\n')
        : `[shinro] ${relative(root, result.outputDirectory)} was generated by an older shinro (format ${result.onDiskFormat}, this is format ${GENERATED_FORMAT}). Run "shinro generate" and commit the result.`
    );
    return 1;
  } catch (error) {
    logger.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

async function runWatch(
  config: ResolvedShinroConfig,
  logger: ShinroLogger,
  root: string
): Promise<number> {
  let started = false;
  const base = resolve(root, config.routes);
  const trigger = (changed: string[]): string => {
    const names = changed.map((file) => relative(base, file));

    if (names.length === 0) {
      return '';
    }

    return `${names.slice(0, 2).join(', ')}${
      names.length > 2 ? ` +${names.length - 2} more` : ''
    }  `;
  };

  await watch({
    config,
    initial: 'report',
    keepAlive: true,
    logger,
    onGenerate: (result, changed) => {
      const drifted = result.written.length + result.removed.length;

      if (drifted === 0) {
        if (started) {
          logger.info(`[shinro] ${trigger(changed)}${dim('up to date')}`);
        }
        return;
      }

      for (const line of [
        ...action('wrote', result.written, root),
        ...action('removed', result.removed, root),
      ]) {
        console.info(line);
      }
    },
  });
  logger.info(`[shinro] watching ${config.routes}`);
  started = true;
  return await new Promise<number>(() => {});
}

function count(routes: number): string {
  return `${routes} route${routes === 1 ? '' : 's'}`;
}

/** Width of the widest verb, so `wrote` and `removed` share a column. */
const LABEL = 'removed'.length;
/** `✓ ` plus the label column plus its trailing space. */
const HANGING = 2 + LABEL + 1;

function action(label: string, paths: string[], root: string): string[] {
  if (paths.length === 0) {
    return [];
  }

  const width = Math.max(process.stdout.columns ?? 80, HANGING + 20);
  const names = paths.map((file) => relative(root, file)).sort();
  const rows: string[] = [];
  let row = '';

  for (const [index, name] of names.entries()) {
    const piece = index === names.length - 1 ? name : `${name},`;

    if (row === '') {
      row = piece;
    } else if (HANGING + row.length + 1 + piece.length <= width) {
      row += ` ${piece}`;
    } else {
      rows.push(row);
      row = piece;
    }
  }
  rows.push(row);

  return rows.map((line, index) =>
    index === 0
      ? `${green('✓')} ${label.padEnd(LABEL)} ${dim(line)}`
      : `${' '.repeat(HANGING)}${dim(line)}`
  );
}
