// Generated by Shinro (format 3). Do not edit.
import type { ShinroRoute, ProjectEnv } from "shinro/app";

export namespace Route {
  export type Handler = ShinroRoute<{
    path: "/users";
    params: {};
    env: ProjectEnv;
  }>;
}
