import { fileURLToPath } from 'node:url';

import { shinro } from 'shinro/tsdown';
import { defineConfig } from 'vite-plus';

const root = fileURLToPath(new URL('.', import.meta.url));

// No Shinro plugin. Routing is generated by `shinro generate` (wired to
// `prepare` and to the build through `tsdown.config.ts`), so all this config does
// is point `vp test` and `vp check` at the project.
//
// `shinro/vite` still ships for projects that would rather keep generation
// inside `vp dev` — it is one adapter among several, and never load-bearing.
export default defineConfig({
  root,
  test: {
    include: ['tests/**/*.test.ts'],
  },
  pack: {
    entry: ['src/server.ts'],
    format: 'esm',
    outDir: 'dist',
    outExtensions: () => ({ js: '.mjs' }),
    platform: 'node',
    target: 'node22',
    unbundle: true,
    dts: false,
    plugins: [shinro()],
  },
});
