import { fileURLToPath } from 'node:url';

import { shinro } from 'shinro/tsdown';
import { defineConfig } from 'vite-plus';

const root = fileURLToPath(new URL('.', import.meta.url));

// Routing is generated by `shinro generate` — wired to `prepare` for the source
// tree, and to `pack` below through the `shinro/tsdown` adapter for the build.
//
// `shinro/vite` is the other adapter, for projects that would rather keep
// generation inside `vp dev`. Neither is load-bearing.
export default defineConfig({
  root,
  test: {
    include: ['tests/**/*.test.ts'],
  },
  pack: {
    entry: ['src/server.ts'],
    format: 'esm',
    outDir: 'dist',
    outExtensions: () => ({ js: '.mjs' }),
    platform: 'node',
    target: 'node22',
    unbundle: true,
    dts: false,
    plugins: [shinro()],
  },
});
