export const ENTRY_ID = 'daroyan/entry';
export const ENTRY_FILE = 'entry.ts';
export const HTTP_METHODS = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'OPTIONS',
] as const;
export const GENERATED_NOTICE =
  '// Generated by Daroyan (format 1). Do not edit.';
/**
 * Every top-level name Daroyan may own inside its generated directory,
 * including the transient lock. Used to tell an existing generated directory
 * apart from a directory that holds someone else's files, so the check cannot
 * be fooled by a generation that is still in progress.
 */
export const GENERATED_ENTRIES = [
  '.lock',
  'client.ts',
  'daroyan.d.ts',
  'modules.d.ts',
  ENTRY_FILE,
  'manifest.json',
  'rpc.ts',
  'types',
] as const;
/**
 * Names Daroyan generated in earlier versions. They are still recognised as
 * Daroyan's own output so an upgrade is not mistaken for a foreign directory,
 * and they are deleted on the next generation.
 *
 * `entry.d.ts` held the ambient `daroyan/entry` declaration before the runtime
 * entry became a real `entry.ts`; TypeScript drops a `.d.ts` shadowed by a
 * same-named `.ts`, so the declaration moved to `modules.d.ts`.
 */
export const LEGACY_GENERATED_ENTRIES = ['entry.d.ts'] as const;
