export const ENTRY_ID = 'daroyan/entry';
export const RESOLVED_ENTRY_ID = `\0${ENTRY_ID}`;
export const HTTP_METHODS = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
  'OPTIONS',
] as const;
export const GENERATED_NOTICE =
  '// Generated by Daroyan (format 1). Do not edit.';
